version: '3.5'
services:
  postgres:
    build:
      dockerfile: Dockerfile
      context: './postgres'
    environment:
      - POSTGRES_PASSWORD=qwer
      - POSTGRES_USER=postgres
      - POSTGRES_DB=thesis_messanger
    networks:
      - webreport-network-dev
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: './nginx'
    ports:
      - "80:8075"
    networks:
      - webreport-network-dev
  api:
    build:
      dockerfile: Dockerfile
      context: './server'
    environment:
      spring.datasource.url: "jdbc:postgresql://postgres:5432/thesis_messanger"
      spring.flyway.url: "jdbc:postgresql://postgres:5432/thesis_messanger"
    networks:
      - webreport-network-dev
    depends_on:
      - "postgres"
    ports:
      - "8075:8075"
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    networks:
      - webreport-network-dev
    ports:
      - "3000:3000"
networks:
  webreport-network-dev:
  #name: webreport-network